version: '3'

services:
  v2ray:
    build: .
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    restart: always
    ports:
      - "443:443"  # Порт для HTTPS
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./key.pem:/etc/v2ray/key.pem
      - ./cert.pem:/etc/v2ray/cert.pem
    
